import { headers } from 'next/headers'

import { Providers } from "./providers";

import { cookieToInitialState } from 'wagmi'
import { config } from "../../config";
import Web3ModalProvider from "../../context";

// UI/UX
import Navbar from '../../components/Header';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <html lang="en">
      <body>
        <Providers>
        <Web3ModalProvider initialState={initialState}>
          <Navbar />
          {children}
          </Web3ModalProvider>
        </Providers>
      </body>
    </html>
  );
}
